version: '3'

services:
  web:
    image: nginx:stable
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/opt/app/static:ro
      - media:/opt/app/media:ro
    ports:
      - ${HTTP_EXPOSED_PORT}:80
    depends_on:
      - backend
    restart: always

  backend:
    image: app/backend:latest
    environment:
      MIGRATE: ${MIGRATE}
      DEBUG: ${DEBUG}
      DEVELOPMENT: ${DEVELOPMENT}
      COLLECT_STATIC: ${COLLECT_STATIC}
      COMPILE_MESSAGES: ${COMPILE_MESSAGES}
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOSTNAME}/${DB_NAME}
      MEDIA_ROOT: /opt/app/media
    volumes:
      - .:/opt/app
      - static:/opt/app/static
      - media:/opt/app/media
      - locale:/opt/app/locale
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    hostname: ${DB_HOSTNAME}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always

volumes:
  postgres_data: {}
  static: {}
  media: {}
  locale: {}
